# Ghostty configuration.
#
# Run `ghostty +show-config --default --docs` to view all available options,
# or see https://ghostty.org/docs/config

font-family = JetBrains Mono
font-size = 15

window-padding-x = 0
maximize = true

theme = light:Selenized Light,dark:Selenized Dark

macos-titlebar-style = tabs

shell-integration-features = ssh-env

keybind = cmd+left=previous_tab
keybind = cmd+right=next_tab
keybind = cmd+shift+left=move_tab:-1
keybind = cmd+shift+right=move_tab:1
keybind = ctrl+end=unbind
# ctrl+fn+down/up == ctrl+page_down/up on macOS; swallow them
keybind = ctrl+page_down=ignore
keybind = ctrl+page_up=ignore
