#!/bin/sh

set -e

TO_HOST=localhost
if [ "$#" -eq 1 ]; then
    TO_HOST="$1"
fi

isLocal() { [ "$TO_HOST" = "localhost" ]; }

run_cmd() {
    echo "$*" >&2
    "$@"
}

mkdirp() {
    dir="$1"
    if [ "$TO_HOST" = localhost ]; then
        run_cmd mkdir -p "$HOME/$1"
    else
        run_cmd ssh "$TO_HOST" "mkdir -p $1"
    fi
}

do_copy() {
    from="$PWD/$1"
    to="$2"
    if [ "$TO_HOST" = localhost ]; then
        to="$HOME/$to"
        unlink "$to" || true
#        run_cmd cp "$from" "$to"
        run_cmd ln -s "$from" "$to"

    else
        run_cmd scp -r "$from" "$TO_HOST:$to"
    fi
}

install_nix_tools() {
    nix profile install 'nixpkgs#tmux' || true
    nix profile install 'nixpkgs#neovim' || true
    nix profile install 'nixpkgs#eza' || true
    nix profile install 'nixpkgs#fzf' || true
    nix profile install 'nixpkgs#zoxide' || true
    nix profile install 'nixpkgs#ripgrep' || true
    nix profile install 'nixpkgs#git' || true
    nix profile install 'nixpkgs#delta' || true
    nix profile install 'nixpkgs#atuin' || true
}

do_copy zshrc .zshrc
mkdirp .zsh/completion
do_copy _bazel .zsh/completion/_bazel
do_copy gitstatus.py .gitstatus.py
do_copy fzf_bz_preview.sh .fzf_bz_preview.sh

do_copy tmux.conf .tmux.conf

mkdirp .config/nvim
do_copy init.vim .config/nvim/init.vim

do_copy gitconfig .gitconfig
do_copy wezterm.lua .wezterm.lua

if isLocal; then
    TPM_PATH=~/.tmux/plugins/tpm
    if [ ! -d "$TPM_PATH" ]; then
        git clone https://github.com/tmux-plugins/tpm $TPM_PATH || git -C $TPM_PATH pull
    fi
fi

install_nix_tools
