#!/bin/sh

set -e
#set pipefail

if [ "$#" -eq 0 ]; then
    echo "Not enough args" >&2
    exit 1
fi

to="$1"
myname=$(basename "$0")

files=$(ls -1)

copy_cmd() {
    from_file="$1"
    scp -r "$from_file" "$to:.$from_file"
}

for file in $files
do
    if [ "$myname" != "$file" ]; then
        copy_cmd $file
    fi
done
